fos_ck_editor:
    default_config: default
    configs:
        default:
            # default toolbar plus Format button
            toolbar:
                - [ Bold, Italic, Underline, -, Cut, Copy, Paste,
                    PasteText, PasteFromWord, -, Undo, Redo, -,
                    NumberedList, BulletedList, -,
                    -, Link, Unlink, -, Blockquote]
                - [ Format, Maximize, Source ]

            filebrowserBrowseRoute: admin_app_sonatamediamedia_ckeditor_browser
            filebrowserImageBrowseRoute: admin_app_sonatamediamedia_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadMethod: form
            filebrowserUploadRoute: admin_app_sonatamediamedia_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_app_sonatamediamedia_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default
                format: big
